# Generated by Django 3.0.5 on 2020-04-24 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_footeraboutus_footertext'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footeraboutus',
            options={'verbose_name_plural': 'Footer About Us'},
        ),
        migrations.AlterModelOptions(
            name='footertext',
            options={'verbose_name_plural': 'Footer Text'},
        ),
    ]
