# Generated by Django 3.1.1 on 2020-09-22 19:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('base', '0003_auto_20200424_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('keywords', models.CharField(help_text='Small text above title', max_length=255)),
                ('body', wagtail.core.fields.RichTextField()),
                ('section_titles', models.CharField(help_text='Title to describe the collection of links', max_length=50)),
                ('important_articles', wagtail.core.fields.StreamField([('important_articles', wagtail.core.blocks.StructBlock([('items', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['blog.ArticlePage'])))]))], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
