# Generated by Django 3.1.1 on 2020-09-22 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='section_titles',
            new_name='section_title',
        ),
    ]
