# Generated by Django 2.2.7 on 2019-11-08 16:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='featured_section',
            field=models.ForeignKey(blank=True, help_text='This is what will be shown below the navbar (e.g. latest articles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2',
            field=models.ForeignKey(blank=True, help_text='This is what will be shown below the navbar (e.g. latest articles)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page', verbose_name='Featured Section'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_2_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='featured_section_title',
            field=models.CharField(blank=True, help_text='Title to display above the promo copy', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(blank=True, help_text='Profile photo for header', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(help_text='Information in header', null=True),
        ),
    ]
