# Generated by Django 2.2.7 on 2019-11-19 17:47

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191108_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Information in header', null=True),
        ),
    ]
