# Generated by Django 2.2.3 on 2019-07-23 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='text',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
