# Generated by Django 2.2.7 on 2019-11-13 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(help_text='Your Facebook page URL')),
                ('instagram', models.URLField(help_text='Your Instagram Profile')),
                ('trip_advisor', models.URLField(help_text='Your Trip Advisor page URL')),
                ('youtube', models.URLField(help_text='Your YouTube channel or user account URL')),
                ('vimeo', models.URLField(help_text='Your Vimeo channel')),
                ('github', models.URLField(help_text='Your Github profile')),
                ('twitter', models.URLField(help_text='Your Twitter Link')),
                ('linkedin', models.URLField(help_text='Your LinkedIn Link')),
                ('stackoverflow', models.URLField(help_text='Your Stack Overflow Profile')),
                ('indiehackers', models.URLField(help_text='Your Indie Hackers Profile')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
