# Generated by Django 2.2.7 on 2019-11-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialmediasettings',
            name='facebook',
            field=models.URLField(blank=True, help_text='Your Facebook page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='github',
            field=models.URLField(blank=True, help_text='Your Github profile', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='indiehackers',
            field=models.URLField(blank=True, help_text='Your Indie Hackers Profile', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='instagram',
            field=models.URLField(blank=True, help_text='Your Instagram Profile', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(blank=True, help_text='Your LinkedIn Link', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='stackoverflow',
            field=models.URLField(blank=True, help_text='Your Stack Overflow Profile', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='trip_advisor',
            field=models.URLField(blank=True, help_text='Your Trip Advisor page URL', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='twitter',
            field=models.URLField(blank=True, help_text='Your Twitter Link', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='vimeo',
            field=models.URLField(blank=True, help_text='Your Vimeo channel', null=True),
        ),
        migrations.AlterField(
            model_name='socialmediasettings',
            name='youtube',
            field=models.URLField(blank=True, help_text='Your YouTube channel or user account URL', null=True),
        ),
    ]
