# Generated by Django 2.2.7 on 2019-11-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20191113_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='codepen',
            field=models.URLField(blank=True, help_text='Your Codepen Profile', null=True),
        ),
    ]
