# Generated by Django 2.2.7 on 2019-11-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_socialmediasettings_codepen'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialmediasettings',
            name='orcid',
            field=models.URLField(blank=True, help_text='Your ORCID profile', null=True),
        ),
    ]
