# Generated by Django 2.2.7 on 2019-11-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_generalsettings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='people',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='people',
            name='last_name',
        ),
        migrations.AddField(
            model_name='people',
            name='description',
            field=models.TextField(null=True, verbose_name='Short summary'),
        ),
        migrations.AddField(
            model_name='people',
            name='name',
            field=models.CharField(blank=True, max_length=254, null=True, verbose_name='Name'),
        ),
    ]
