# Generated by Django 2.2.7 on 2019-11-24 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20191124_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='site',
        ),
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.DeleteModel(
            name='SocialMediaSettings',
        ),
    ]
