# Generated by Django 2.2.7 on 2019-11-18 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='translation',
            new_name='translated',
        ),
    ]
