# Generated by Django 2.2.7 on 2019-11-19 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191118_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogindexpage',
            name='featured_article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='blog.BlogPage'),
        ),
    ]
