# Generated by Django 2.2.7 on 2019-11-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191124_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='allow_comments',
            field=models.BooleanField(default=True),
        ),
    ]
