# Generated by Django 2.2.7 on 2019-12-03 20:45

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    replaces = [('resume', '0001_initial'), ('resume', '0002_resumepage_social_profiles'), ('resume', '0003_auto_20191111_2038'), ('resume', '0004_auto_20191111_2041'), ('resume', '0005_remove_resumepage_social_profiles'), ('resume', '0006_resumepage_social_profiles'), ('resume', '0007_auto_20191111_2058'), ('resume', '0008_auto_20191112_1746'), ('resume', '0009_resumepage_header_text'), ('resume', '0010_auto_20191112_1757'), ('resume', '0011_resumepage_career_summary'), ('resume', '0012_resumepage_work_experience'), ('resume', '0013_auto_20191112_1828'), ('resume', '0014_auto_20191112_1936'), ('resume', '0015_resumepage_skills_tools'), ('resume', '0016_auto_20191112_2012'), ('resume', '0017_auto_20191112_2031'), ('resume', '0018_resumepage_miscelaneous'), ('resume', '0019_auto_20191112_2108'), ('resume', '0020_resumepage_interests')]

    initial = True

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtaildocs', '0010_document_file_hash'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('pdf_link', models.ForeignKey(blank=True, help_text='PDF version of the resume', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document')),
                ('profile_image', models.ForeignKey(blank=True, help_text='Profile photo to show at the top', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
                ('social_profiles', wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('social_network', wagtail.core.blocks.URLBlock(label='Profile to link to', required=True)), ('name', wagtail.core.blocks.CharBlock(label='Name to show on website', required=True)), ('fa_icon', wagtail.core.blocks.CharBlock(label='Font Awesome Icon to use, for example fa-linkedin-in', required=True))]))], blank=True, help_text='Links to social profiles', null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('name', models.CharField(default='a', help_text='Your name', max_length=250)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('subtitle', models.CharField(default='a', help_text='Subtitle, under the name', max_length=250)),
                ('career_summary', models.TextField(default='a')),
                ('work_experience', wagtail.core.fields.StreamField([('work', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('where', wagtail.core.blocks.CharBlock(required=True)), ('start_date', wagtail.core.blocks.DateBlock(required=True)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True)), ('tags', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))]))], blank=True, help_text='Work Experience', null=True)),
                ('skills_tools', wagtail.core.fields.StreamField([('skills_tools', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=25, required=True)), ('percentage', wagtail.core.blocks.IntegerBlock(help_text='Confidence in this skill', max_value=100, min_value=0, required=True))])))]))], blank=True, help_text='Skills and Tools', null=True)),
                ('education', wagtail.core.fields.StreamField([('education', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('where', wagtail.core.blocks.CharBlock(max_length=75, required=True)), ('start_date', wagtail.core.blocks.DateBlock(required=True)), ('end_date', wagtail.core.blocks.DateBlock(required=False))]))], blank=True, help_text='Education', null=True)),
                ('other_skills', wagtail.core.fields.StreamField([('other_skills', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, help_text='Other Skills', null=True)),
                ('miscellaneous', wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True)),
                ('languages', wagtail.core.fields.StreamField([('language', wagtail.core.blocks.StructBlock([('language', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('proficiency', wagtail.core.blocks.CharBlock(max_length=50, required=True))]))], blank=True, null=True)),
                ('interests', wagtail.core.fields.StreamField([('interest', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=20, required=True))]))], blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
