# Generated by Django 2.2.7 on 2020-03-28 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_squashed_0020_resumepage_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='career_summary',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='name',
            field=models.CharField(help_text='Your name', max_length=250),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='subtitle',
            field=models.CharField(help_text='Subtitle, under the name', max_length=250),
        ),
    ]
