# Generated by Django 2.2.7 on 2019-11-11 20:38

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_resumepage_social_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='social_profiles',
            field=wagtail.core.fields.StreamField([('social_network', wagtail.core.blocks.URLBlock(help_text='Profile to link to')), ('fa_icon', wagtail.core.blocks.CharBlock(help_text='Font Awesome Icon to use, for example fa-linkedin-in'))], blank=True, verbose_name='List of social links'),
        ),
    ]
