# Generated by Django 2.2.7 on 2019-11-11 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20191111_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='social_profiles',
        ),
    ]
