# Generated by Django 2.2.7 on 2019-11-12 17:46

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20191111_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='header_text',
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='social_profiles',
            field=wagtail.core.fields.StreamField([('social_link', wagtail.core.blocks.StructBlock([('social_network', wagtail.core.blocks.URLBlock(label='Profile to link to', required=True)), ('name', wagtail.core.blocks.CharBlock(label='Name to show on website', required=True)), ('fa_icon', wagtail.core.blocks.CharBlock(label='Font Awesome Icon to use, for example fa-linkedin-in', required=True))]))], blank=True, help_text='Links to social profiles', null=True),
        ),
    ]
