# Generated by Django 2.2.7 on 2019-11-12 17:48

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20191112_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='header_text',
            field=wagtail.core.fields.StreamField([('name', wagtail.core.blocks.CharBlock(help_text='Your name', max_length=250, required=True)), ('subtitle', wagtail.core.blocks.CharBlock(help_text='Subtitle, under the name', max_length=250, required=True)), ('email', wagtail.core.blocks.EmailBlock(help_text='Your e-mail', required=False)), ('phone', wagtail.core.blocks.CharBlock(help_text='Your phone number', max_length=15, required=False))], default='', help_text='Header text'),
            preserve_default=False,
        ),
    ]
