# Generated by Django 2.2.7 on 2019-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_resumepage_header_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resumepage',
            name='header_text',
        ),
        migrations.AddField(
            model_name='resumepage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='name',
            field=models.CharField(default='a', help_text='Your name', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resumepage',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='subtitle',
            field=models.CharField(default='a', help_text='Subtitle, under the name', max_length=250),
            preserve_default=False,
        ),
    ]
