# Generated by Django 2.2.7 on 2019-11-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20191112_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='career_summary',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
