# Generated by Django 2.2.7 on 2019-11-12 18:28

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_resumepage_work_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumepage',
            name='work_experience',
            field=wagtail.core.fields.StreamField([('title', wagtail.core.blocks.CharBlock(required=True)), ('where', wagtail.core.blocks.CharBlock(required=True)), ('start_date', wagtail.core.blocks.DateBlock(required=True)), ('end_date', wagtail.core.blocks.DateBlock(required=False)), ('description', wagtail.core.blocks.RichTextBlock(required=True)), ('tags', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock()))], blank=True, help_text='Work Experience', null=True),
        ),
    ]
