# Generated by Django 2.2.7 on 2019-11-12 20:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20191112_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='skills_tools',
            field=wagtail.core.fields.StreamField([('skills_tools', wagtail.core.blocks.StructBlock([('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=25, required=True)), ('percentage', wagtail.core.blocks.IntegerBlock(help_text='Confidence in this skill', max_value=100, min_value=0, required=True))]))), ('title', wagtail.core.blocks.CharBlock(required=True))], classname='full title'))], blank=True, help_text='Skills and Tools', null=True),
        ),
    ]
