# Generated by Django 2.2.7 on 2019-11-12 20:31

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0016_auto_20191112_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='education',
            field=wagtail.core.fields.StreamField([('education', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('where', wagtail.core.blocks.CharBlock(max_length=75, required=True)), ('start_date', wagtail.core.blocks.DateBlock(required=True)), ('end_date', wagtail.core.blocks.DateBlock(required=False))]))], blank=True, help_text='Education', null=True),
        ),
        migrations.AddField(
            model_name='resumepage',
            name='other_skills',
            field=wagtail.core.fields.StreamField([('other_skills', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True))]))], blank=True, help_text='Other Skills', null=True),
        ),
        migrations.AlterField(
            model_name='resumepage',
            name='skills_tools',
            field=wagtail.core.fields.StreamField([('skills_tools', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(required=True)), ('skills', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=25, required=True)), ('percentage', wagtail.core.blocks.IntegerBlock(help_text='Confidence in this skill', max_value=100, min_value=0, required=True))])))]))], blank=True, help_text='Skills and Tools', null=True),
        ),
    ]
