# Generated by Django 2.2.7 on 2019-11-12 21:00

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_auto_20191112_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='miscelaneous',
            field=wagtail.core.fields.StreamField([('content', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(max_length=50, required=True)), ('description', wagtail.core.blocks.TextBlock(required=True))]))], blank=True, null=True),
        ),
    ]
