# Generated by Django 2.2.7 on 2019-11-13 10:32

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0019_auto_20191112_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumepage',
            name='interests',
            field=wagtail.core.fields.StreamField([('interest', wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(max_length=20, required=True))]))], blank=True, null=True),
        ),
    ]
